### main  page
GET http://localhost:3000/

### get all expenses
GET http://localhost:3000/api/exp_all

### get post by ID
GET http://localhost:3000/api/exp/10

### Create expense
POST http://localhost:3000/api/exp
Content-Type:  application/json

{
    "cat_id": "2",
    "comment": "Test 1",
    "date": "2023-12-29",
    "amount": -30
}

### Edit expense by ID
PUT http://localhost:3000/api/exp/1
Content-Type:  application/json

{
    "cat_id": "1",
    "comment": "Kruopos",
    "date": "2023-12-29",
    "amount": -3
}

### Delete post
DELETE  http://localhost:3000/api/exp/10

### get all expenses categories
GET http://localhost:3000/api/cats

### REGISTER User
POST http://localhost:3000/api/auth/reg
Content-Type: application/json

{
  "email": "james@secure2.com",
  "password": "123456"
}

### LOG IN User
POST http://localhost:3000/api/auth/log
Content-Type: application/json

{
  "email": "james@secure2.com",
  "password": "123456"
}